version: '2'

volumes:
  postgres_data: {}
  postgres_backup: {}
  caddy: {}
services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    depends_on:
      - postgres
      - redis
#      - sftp
    env_file: .env

    command: /gunicorn.sh

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    env_file: .env

  caddy:
    build:
      context: .
      dockerfile: ./compose/production/caddy/Dockerfile
    depends_on:
      - django
    volumes:
      - caddy:/root/.caddy
    env_file: .env
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"

  redis:
    image: redis:3.0

#  sftp:
#    image: atmoz/sftp:alpine
#    ports:
#      - "2222:22"
#    volumes:
#      - /var/upload:/home/sftp/upload
#    command: sftp:sftp:1001:100

