# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-04 09:04
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='问题')),
                ('reply', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='答案')),
                ('seo_key', models.CharField(blank=True, max_length=200, null=True, verbose_name='关键词')),
                ('seo_desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='页面描述')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '问答',
                'verbose_name_plural': '问答',
            },
        ),
        migrations.CreateModel(
            name='Shizhi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='试纸名称')),
                ('slug', models.CharField(max_length=20, unique=True)),
                ('bianhao', models.CharField(max_length=6, unique=True, verbose_name='试纸编号')),
                ('cover', models.ImageField(null=True, upload_to='shizhi', verbose_name='封面图')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='试纸介绍')),
                ('seo_key', models.CharField(blank=True, max_length=200, null=True, verbose_name='关键词')),
                ('seo_desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='页面描述')),
                ('is_taozhuang', models.BooleanField(default=False, verbose_name='是否是套装')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '试纸',
                'verbose_name_plural': '试纸',
            },
        ),
        migrations.AddField(
            model_name='questions',
            name='shizhi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shizhi.Shizhi'),
        ),
    ]
