# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-27 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shizhi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shizhi',
            name='cover',
            field=models.ImageField(upload_to='shizhi', verbose_name='封面图', null=True),
        ),
    ]
