# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-02 01:20
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shizhi', '0002_shizhi_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='问题')),
                ('reply', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='答案')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('shizhi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shizhi.Shizhi')),
            ],
            options={
                'verbose_name': '问答',
                'verbose_name_plural': '问答',
            },
        ),
    ]
