# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-09 02:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shizhi', '0002_remove_shizhi_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShizhiType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='试纸类型')),
                ('slug', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='shizhi',
            name='cover_url',
            field=models.URLField(blank=True, verbose_name='封面图URL'),
        ),
        migrations.AddField(
            model_name='shizhi',
            name='shizhi_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shizhi.ShizhiType'),
        ),
    ]
