# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-09 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shizhi', '0003_auto_20180109_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shizhi',
            name='shizhi_type',
            field=models.CharField(choices=[('xueye', '血液'), ('tuoye', '唾液')], default='xueye', max_length=10),
        ),
        migrations.DeleteModel(
            name='ShizhiType',
        ),
    ]
