# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-03 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shizhi', '0003_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shizhi',
            name='shiyong',
        ),
        migrations.AddField(
            model_name='shizhi',
            name='bianhao',
            field=models.CharField(max_length=6, unique=True, verbose_name='试纸编号'),
            preserve_default=False,
        ),
    ]
