# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-09 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shizhi', '0004_auto_20180109_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='shizhi',
            name='fangan',
            field=models.CharField(choices=[('danfen', '单份试纸'), ('two-week', '两周检测方案'), ('four-week', '四周检测方案'), ('eight-week', '八周以上检测方案')], default='danfen', max_length=10),
        ),
    ]
