# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-09 03:01
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shizhi', '0005_shizhi_fangan'),
    ]

    operations = [
        migrations.AddField(
            model_name='shizhi',
            name='other',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='其他信息'),
        ),
    ]
