# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-07 02:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0003_set_site_domain_and_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad1', models.TextField()),
                ('ad2', models.TextField()),
                ('ad3', models.TextField()),
                ('ad4', models.TextField()),
                ('ad5', models.TextField()),
                ('ad6', models.TextField()),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ad', to='sites.Site')),
            ],
            options={
                'verbose_name': '广告',
                'verbose_name_plural': '广告',
            },
        ),
        migrations.CreateModel(
            name='ExtendSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo')),
                ('seo_title', models.CharField(blank=True, max_length=200, verbose_name='首页标题')),
                ('seo_key', models.CharField(blank=True, max_length=200, verbose_name='首页关键词')),
                ('seo_desc', models.CharField(blank=True, max_length=255, verbose_name='首页页面描述')),
                ('baidu_analytics', models.CharField(blank=True, max_length=40, verbose_name='百度统计ID')),
                ('google_analytics', models.CharField(blank=True, max_length=40, verbose_name='Google统计ID')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extend', to='sites.Site')),
            ],
            options={
                'verbose_name': 'SIte 扩展',
                'verbose_name_plural': 'SIte 扩展',
            },
        ),
        migrations.CreateModel(
            name='FriendLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=255)),
                ('logo', models.ImageField(blank=True, upload_to='friendlink/')),
                ('site', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friendlink', to='sites.Site')),
            ],
            options={
                'verbose_name': '友情链接',
                'verbose_name_plural': '友情链接',
            },
        ),
    ]
