# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-08 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0002_auto_20180108_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendsite',
            name='analytics',
            field=models.TextField(blank=True, max_length=40, verbose_name='统计代码'),
        ),
    ]
