# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-04 09:14
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0003_set_site_domain_and_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '发布')], default='draft', max_length=10)),
                ('name', models.CharField(max_length=255, verbose_name='文章名')),
                ('slug', models.TextField(editable=False, max_length=16, unique=True)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='正文')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('stick', models.BooleanField(default=False, verbose_name='是否置顶')),
                ('views', models.PositiveIntegerField(default=5268, verbose_name='阅读统计量')),
                ('seo_key', models.CharField(blank=True, max_length=200, null=True, verbose_name='关键词')),
                ('seo_desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='页面描述')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aritlce', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'ordering': ('-publish',),
            },
        ),
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('slug', models.TextField(editable=False, max_length=16, unique=True)),
                ('is_nav', models.BooleanField(default=False, verbose_name='是否在nav显示')),
            ],
            options={
                'verbose_name': '文章分类',
                'verbose_name_plural': '文章分类',
            },
        ),
        migrations.CreateModel(
            name='ExtendSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo')),
                ('seo_title', models.CharField(blank=True, max_length=200, verbose_name='首页标题')),
                ('seo_key', models.CharField(blank=True, max_length=200, verbose_name='首页关键词')),
                ('seo_desc', models.CharField(blank=True, max_length=255, verbose_name='首页页面描述')),
                ('baidu_analytics', models.CharField(blank=True, max_length=40, verbose_name='百度统计ID')),
                ('google_analytics', models.CharField(blank=True, max_length=40, verbose_name='Google统计ID')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extend', to='sites.Site')),
            ],
            options={
                'verbose_name': 'SIte 扩展',
                'verbose_name_plural': 'SIte 扩展',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='article.ArticleCategory', verbose_name='文章分类'),
        ),
    ]
