# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-08 12:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendsite',
            name='site',
        ),
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.DeleteModel(
            name='ExtendSite',
        ),
    ]
