# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-05 02:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20171205_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='article', to='article.ArticleCategory'),
            preserve_default=False,
        ),
    ]
