# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-18 05:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aritlce', to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='article.ArticleCategory', verbose_name='文章分类'),
        ),
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.TextField(max_length=255, verbose_name='文章名'),
        ),
    ]
