# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-22 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20171218_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='views',
            field=models.PositiveIntegerField(default=5268, verbose_name='阅读统计量'),
        ),
    ]
