# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-22 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_article_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecategory',
            name='is_nav',
            field=models.BooleanField(default=False, verbose_name='是否在nav显示'),
        ),
    ]
