# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-25 05:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_set_site_domain_and_name'),
        ('article', '0006_articlecategory_is_nav'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extend', to='sites.Site')),
            ],
            options={
                'verbose_name': 'SIte 扩展',
                'verbose_name_plural': 'SIte 扩展',
            },
        ),
    ]
